[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
build = "build.rs"
description = "Code generation library for Rusoto."
license = "MIT"
name = "rusoto_codegen"
repository = "https://github.com/rusoto/rusoto"
version = "0.4.0"

[build-dependencies.serde_codegen]
optional = true
version = "0.8.0"

[dependencies]
Inflector = "0.6.0"
lazy_static = "0.2.1"
regex = "0.1.65"
serde = "0.8.0"
serde_json = "0.8.0"
reqwest = "0.2.0"

[dependencies.clippy]
optional = true
version = "0.0"

[dependencies.serde_codegen]
optional = true
version = "0.8.14"

[dependencies.serde_derive]
optional = true
version = "0.8.19"

[features]
default = ["serde_codegen"]
nightly-testing = ["clippy", "unstable"]
unstable = ["serde_derive"]
